USE [master]
GO

/****** Object:  Database [FoodStore]    Script Date: 10/3/2016 9:49:07 PM ******/
CREATE DATABASE [FoodStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLSERVER2K14\MSSQL\DATA\FoodStore.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FoodStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLSERVER2K14\MSSQL\DATA\FoodStore_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FoodStore] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FoodStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FoodStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FoodStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FoodStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FoodStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [FoodStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FoodStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FoodStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FoodStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FoodStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FoodStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FoodStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FoodStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FoodStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FoodStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FoodStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FoodStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FoodStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FoodStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FoodStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FoodStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FoodStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FoodStore] SET RECOVERY FULL 
GO

ALTER DATABASE [FoodStore] SET  MULTI_USER 
GO

ALTER DATABASE [FoodStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FoodStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FoodStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FoodStore] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FoodStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FoodStore] SET  READ_WRITE 
GO


